"""Add success and goal_minute to alerts

Revision ID: a5e0264baf41
Revises: 712c5ea555a3
Create Date: 2026-06-15 21:22:11.773903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e0264baf41'
down_revision: Union[str, Sequence[str], None] = '712c5ea555a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('success', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('goal_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'goal_minute')
    op.drop_column('alerts', 'success')
    # ### end Alembic commands ###
